// This file is automatically generated. Do not edit it manually.
// Import the typeDefs and resolvers from their respective files
// and export them for use in the Apollo server setup
// This file is automatically generated. Do not edit it manually.
import typeDefs from './typeDefs.js';
import resolvers from './resolvers.js';

export { typeDefs, resolvers };
